const KEY='kurumFinansAsistanim.v1';
const CONFIG_KEY='kurumFinansAsistanim.cloud';
const DEVICE_KEY='kurumFinansAsistanim.deviceName';
const defaultState={debts:[],expenses:[],payments:[],budget:{orgName:'',income:0,fixedExpenses:0,reserve:0},updatedAt:null};
let state=loadState();
let cloud=loadCloud();
let sb=null, session=null, deferredPrompt=null, syncing=false;
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
const money=n=>new Intl.NumberFormat('tr-TR',{style:'currency',currency:'TRY',maximumFractionDigits:0}).format(Number(n)||0);
const fmt=n=>new Intl.NumberFormat('tr-TR',{maximumFractionDigits:2}).format(Number(n)||0);
const todayISO=()=>{const d=new Date();const z=d.getTimezoneOffset()*60000;return new Date(d-z).toISOString().slice(0,10)};
const parseDate=s=>s?new Date(`${s}T12:00:00`):null;
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const uid=()=>crypto?.randomUUID?.()||Date.now().toString(36)+Math.random().toString(36).slice(2);
const deviceName=()=>localStorage.getItem(DEVICE_KEY)||'Bu telefon';
function clone(v){return JSON.parse(JSON.stringify(v))}
function loadState(){try{return {...clone(defaultState),...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return clone(defaultState)}}
function loadCloud(){try{return JSON.parse(localStorage.getItem(CONFIG_KEY)||'{}')}catch{return {}}}
function saveState(render=true){state.updatedAt=new Date().toISOString();localStorage.setItem(KEY,JSON.stringify(state));if(render)renderAll()}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2300)}
function addMonths(date,n=1){const d=new Date(date);const day=d.getDate();d.setDate(1);d.setMonth(d.getMonth()+n);const last=new Date(d.getFullYear(),d.getMonth()+1,0).getDate();d.setDate(Math.min(day,last));return d}
function normalizeDebt(d){return {id:d.id||uid(),name:d.name||d.ad||'',type:d.type||d.tur||'Diğer',original:+(d.original??d.ilk_tutar)||0,balance:+(d.balance??d.kalan_tutar)||0,rate:+(d.rate??d.faiz_orani)||0,minimum:+(d.minimum??d.aylik_odeme)||0,dueDate:d.dueDate??d.vade_tarihi??'',frequency:d.frequency||d.tekrar||'monthly',notes:d.notes??d.notlar??'',status:d.status||d.durum||((+(d.balance??d.kalan_tutar)||0)<=0?'closed':'active'),addedBy:d.addedBy??d.ekleyen??'',createdAt:d.createdAt??d.olusturma_zamani??new Date().toISOString(),updatedAt:d.updatedAt??d.guncelleme_zamani??new Date().toISOString()}}
function normalizeExpense(x){return {id:x.id||uid(),date:x.date||x.tarih||todayISO(),category:x.category||x.kategori||'Diğer',description:x.description||x.aciklama||'',amount:+(x.amount??x.tutar)||0,method:x.method||x.odeme_yontemi||'Banka',notes:x.notes??x.notlar??'',addedBy:x.addedBy??x.ekleyen??'',createdAt:x.createdAt??x.olusturma_zamani??new Date().toISOString(),updatedAt:x.updatedAt??x.guncelleme_zamani??new Date().toISOString()}}
function normalizePayment(p){return {id:p.id||uid(),debtId:p.debtId||p.borc_id,date:p.date||p.tarih||todayISO(),amount:+(p.amount??p.tutar)||0,notes:p.notes??p.notlar??'',addedBy:p.addedBy??p.ekleyen??'',createdAt:p.createdAt??p.olusturma_zamani??new Date().toISOString()}}
function activeDebts(){return state.debts.map(normalizeDebt).filter(d=>d.status==='active'&&d.balance>0)}
function daysBetween(a,b){return Math.ceil((b-a)/86400000)}
function dueItems(){const now=parseDate(todayISO());return activeDebts().filter(d=>d.dueDate&&d.minimum>0).map(d=>{const date=parseDate(d.dueDate);return {...d,date,days:daysBetween(now,date),amount:Math.min(d.balance,d.minimum||d.balance)}}).sort((a,b)=>a.date-b.date)}
function monthKey(s=todayISO()){return s.slice(0,7)}
function currentMonthExpenses(){const m=monthKey();return state.expenses.map(normalizeExpense).filter(x=>x.date?.startsWith(m))}
function currentMonthPayments(){const m=monthKey();return state.payments.map(normalizePayment).filter(x=>x.date?.startsWith(m))}
function calcCapacity(){return Math.max(0,(+state.budget.income||0)-(+state.budget.fixedExpenses||0)-(+state.budget.reserve||0))}
function assistantTip(){const debts=activeDebts(), expenses=currentMonthExpenses().reduce((s,x)=>s+x.amount,0), due=dueItems();const overdue=due.filter(x=>x.days<0);if(overdue.length)return {title:'Gecikmiş ödeme var',body:`${overdue.length} borç ödemesi geçmiş durumda. Toplam ${money(overdue.reduce((s,x)=>s+x.amount,0))} için önce gecikmeyi kapatın.`};const in7=due.filter(x=>x.days>=0&&x.days<=7);if(in7.length)return {title:'Önümüzdeki 7 güne hazırlık',body:`${money(in7.reduce((s,x)=>s+x.amount,0))} yaklaşan borç ödemesi var. Bu tutarı işletme hesabında ayırın.`};if(debts.length){const high=[...debts].sort((a,b)=>b.rate-a.rate)[0];return {title:'Faiz yükünü kontrol edin',body:`En yüksek faizli aktif borç “${high.name}” (%${fmt(high.rate)}). Nakit fazlası varsa öncelikli kapatma adayı bu borç.`}}if(expenses>0)return {title:'Harcama kaydı güncel',body:`Bu ay ${money(expenses)} kurum harcaması kaydedildi. Borç bulunmadığı için nakit rezervini koruyabilirsiniz.`};return {title:'Kayıt ekleyerek başlayın',body:'Kurum borçlarını ve günlük harcamaları eklediğinizde ödeme takvimi ve aylık finans özeti otomatik oluşur.'}}
function renderDashboard(){const debts=activeDebts(), total=debts.reduce((s,d)=>s+d.balance,0), exp=currentMonthExpenses().reduce((s,x)=>s+x.amount,0), pays=currentMonthPayments().reduce((s,x)=>s+x.amount,0), due=dueItems(), in7=due.filter(x=>x.days>=0&&x.days<=7).reduce((s,x)=>s+x.amount,0), overdue=due.filter(x=>x.days<0);$('#totalDebt').textContent=money(total);$('#debtInfo').textContent=debts.length?`${debts.length} aktif borç kaydı`:'Aktif kurum borcu bulunmuyor.';$('#monthExpense').textContent=money(exp);$('#monthOut').textContent=money(exp+pays);$('#next7').textContent=money(in7);$('#overdueCount').textContent=overdue.length;$('#capacity').textContent=money(calcCapacity());const tip=assistantTip();$('#assistantCard').innerHTML=`<strong>${esc(tip.title)}</strong><p class="muted">${esc(tip.body)}</p>`;$('#upcomingMini').innerHTML=due.length?due.slice(0,3).map(d=>dueCard(d)).join(''):empty('Yaklaşan borç ödemesi yok.');const rec=[...state.expenses].map(normalizeExpense).sort((a,b)=>`${b.date}${b.createdAt}`.localeCompare(`${a.date}${a.createdAt}`)).slice(0,3);$('#recentExpenses').innerHTML=rec.length?rec.map(expenseCard).join(''):empty('Henüz kurum harcaması girilmedi.')}
function dueCard(d){const badge=d.days<0?`<span class="badge red">${Math.abs(d.days)} gün gecikti</span>`:d.days===0?'<span class="badge orange">Bugün</span>':`<span class="badge">${d.days} gün</span>`;return `<article class="list-card clickable" data-debt="${d.id}"><div class="main"><strong>${esc(d.name)}</strong><small>${d.date.toLocaleDateString('tr-TR')} · ${badge}</small></div><div class="amount">${money(d.amount)}<small>${esc(d.type)}</small></div></article>`}
function debtCard(d){const p=d.original>0?Math.round((1-d.balance/d.original)*100):0;return `<article class="list-card clickable" data-debt="${d.id}"><div class="main"><strong>${esc(d.name)}</strong><small>${esc(d.type)} · ${d.status==='closed'?'<span class="badge green">Kapandı</span>':`%${Math.max(0,p)} ödendi`}</small></div><div class="amount">${money(d.balance)}<small>${d.dueDate?parseDate(d.dueDate).toLocaleDateString('tr-TR'):'Vade yok'}</small></div></article>`}
function renderDebts(){const q=$('#debtSearch').value.trim().toLocaleLowerCase('tr-TR'),filter=$('#debtFilter').value;let list=state.debts.map(normalizeDebt).filter(d=>(filter==='all'||(filter==='active'&&d.status==='active')||(filter==='closed'&&d.status==='closed'))&&(!q||`${d.name} ${d.type} ${d.notes}`.toLocaleLowerCase('tr-TR').includes(q))).sort((a,b)=>(a.status===b.status?b.createdAt.localeCompare(a.createdAt):a.status==='active'?-1:1));$('#debtList').innerHTML=list.length?list.map(debtCard).join(''):empty(filter==='active'?'Aktif borç bulunmuyor.':'Borç kaydı bulunmuyor.')}
function expenseCard(x){return `<article class="list-card clickable" data-expense="${x.id}"><div class="main"><strong>${esc(x.description)}</strong><small>${parseDate(x.date).toLocaleDateString('tr-TR')} · ${esc(x.category)}${x.addedBy?` · ${esc(x.addedBy)}`:''}</small></div><div class="amount">${money(x.amount)}<small>${esc(x.method)}</small></div></article>`}
function populateMonths(){const select=$('#expenseMonth'), current=monthKey();const months=new Set([current,...state.expenses.map(x=>normalizeExpense(x).date.slice(0,7)).filter(Boolean)]);const sorted=[...months].sort().reverse();const old=select.value||current;select.innerHTML=sorted.map(m=>{const [y,mo]=m.split('-');const label=new Date(+y,+mo-1,1).toLocaleDateString('tr-TR',{month:'long',year:'numeric'});return `<option value="${m}">${label}</option>`}).join('');select.value=sorted.includes(old)?old:current}
function renderExpenses(){populateMonths();const q=$('#expenseSearch').value.trim().toLocaleLowerCase('tr-TR'),m=$('#expenseMonth').value;const list=state.expenses.map(normalizeExpense).filter(x=>x.date.startsWith(m)&&(!q||`${x.description} ${x.category} ${x.method} ${x.notes}`.toLocaleLowerCase('tr-TR').includes(q))).sort((a,b)=>`${b.date}${b.createdAt}`.localeCompare(`${a.date}${a.createdAt}`));const total=list.reduce((s,x)=>s+x.amount,0);$('#expenseList').innerHTML=`<div class="expense-total"><span>Seçili dönem toplamı</span><strong>${money(total)}</strong></div>${list.length?list.map(expenseCard).join(''):empty('Bu dönemde harcama yok.')}`}
function paymentCard(p){const d=state.debts.map(normalizeDebt).find(x=>x.id===p.debtId);return `<article class="list-card"><div class="main"><strong>${esc(d?.name||'Silinmiş borç')}</strong><small>${parseDate(p.date).toLocaleDateString('tr-TR')}${p.addedBy?` · ${esc(p.addedBy)}`:''}</small></div><div class="amount">${money(p.amount)}<small>${esc(p.notes||'Borç ödemesi')}</small></div></article>`}
function renderPayments(){const list=state.payments.map(normalizePayment).sort((a,b)=>`${b.date}${b.createdAt}`.localeCompare(`${a.date}${a.createdAt}`));$('#paymentList').innerHTML=list.length?list.map(paymentCard).join(''):empty('Henüz borç ödemesi yok.')}
function renderCalendar(){const list=dueItems();$('#calendarList').innerHTML=list.length?list.map(d=>dueCard(d)).join(''):empty('Takvimde yaklaşan ödeme yok.')}
function renderBudget(){const f=$('#budgetForm');f.elements.orgName.value=state.budget.orgName||'';f.elements.income.value=state.budget.income||'';f.elements.fixedExpenses.value=state.budget.fixedExpenses||'';f.elements.reserve.value=state.budget.reserve||'';$('#orgEyebrow').textContent=(state.budget.orgName||'ORTAK FİNANS').toLocaleUpperCase('tr-TR');$('#deviceName').value=deviceName()}
function renderPaymentOptions(){const s=$('#paymentForm').elements.debtId;s.innerHTML=activeDebts().map(d=>`<option value="${d.id}">${esc(d.name)} — ${money(d.balance)}</option>`).join('')}
function renderCloud(){const configured=!!(cloud.url&&cloud.key);const online=!!session;$('#syncBadge').textContent=online?'Bulut':configured?'Giriş yok':'Yerel';$('#syncBadge').className=`status-badge ${online?'online':''}`;$('#authBanner').classList.toggle('hidden',online);$('#cloudSummary').innerHTML=online?`<strong>Bağlı:</strong> ${esc(session.user?.email||'Kurum hesabı')}<br>İki telefonda aynı hesapla giriş yapıldığında kayıtlar ortak görünür.`:configured?'Bulut projesi tanımlı; ortak veriler için kurum hesabına giriş yapın.':'Henüz ortak bulut bağlantısı yapılmadı.';$('#logoutBtn').classList.toggle('hidden',!online);$('#cloudStepConfig').classList.toggle('hidden',configured);$('#cloudStepAuth').classList.toggle('hidden',!configured);$('#loggedOutAuth').classList.toggle('hidden',online);$('#loggedInAuth').classList.toggle('hidden',!online);if(online){$('#cloudUserEmail').textContent=session.user?.email||''}}
function renderAll(){renderDashboard();renderDebts();renderExpenses();renderCalendar();renderPayments();renderBudget();renderPaymentOptions();renderCloud()}
function empty(t){return `<div class="empty">${esc(t)}</div>`}
function openView(id){$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));$$('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.view===id));$('#fab').style.display=id==='settings'?'none':'block';window.scrollTo({top:0,behavior:'smooth'})}
function openDebtDialog(d=null){const f=$('#debtForm');f.reset();$('#debtDialogTitle').textContent=d?'Borcu Düzenle':'Yeni Borç';if(d){for(const k of ['id','name','type','original','balance','rate','minimum','dueDate','frequency','notes'])if(f.elements[k])f.elements[k].value=d[k]??''}else{f.elements.dueDate.value=todayISO();f.elements.frequency.value='monthly'}$('#debtDialog').showModal()}
function openExpenseDialog(x=null){const f=$('#expenseForm');f.reset();$('#expenseDialogTitle').textContent=x?'Harcamayı Düzenle':'Yeni Harcama';if(x){for(const k of ['id','date','category','description','amount','method','notes'])if(f.elements[k])f.elements[k].value=x[k]??''}else f.elements.date.value=todayISO();$('#expenseDialog').showModal()}
function openPaymentDialog(debtId=null){renderPaymentOptions();const f=$('#paymentForm');f.reset();f.elements.date.value=todayISO();if(debtId)f.elements.debtId.value=debtId;if(!f.elements.debtId.value){toast('Ödeme için önce aktif borç ekleyin.');return}$('#paymentDialog').showModal()}
function showDebtDetail(id){const d=state.debts.map(normalizeDebt).find(x=>x.id===id);if(!d)return;const payments=state.payments.map(normalizePayment).filter(p=>p.debtId===id).sort((a,b)=>b.date.localeCompare(a.date));$('#debtDetailContent').innerHTML=`<div class="dialog-head"><div><p class="eyebrow">${esc(d.type)}</p><h3>${esc(d.name)}</h3></div><button class="icon-btn" onclick="document.querySelector('#debtDetailDialog').close()">×</button></div><div class="metric-row"><div class="metric"><span>Kalan</span><strong>${money(d.balance)}</strong></div><div class="metric"><span>Faiz</span><strong>%${fmt(d.rate)}</strong></div><div class="metric"><span>Aylık ödeme</span><strong>${money(d.minimum)}</strong></div><div class="metric"><span>Vade</span><strong>${d.dueDate?parseDate(d.dueDate).toLocaleDateString('tr-TR'):'—'}</strong></div></div>${d.notes?`<p class="muted">${esc(d.notes)}</p>`:''}<div class="detail-actions"><button class="primary" data-pay="${d.id}">Ödeme Ekle</button><button class="secondary" data-edit-debt="${d.id}">Düzenle</button></div>${payments.length?`<div><h3>Son Ödemeler</h3>${payments.slice(0,4).map(paymentCard).join('')}</div>`:''}<button class="danger-btn" data-delete-debt="${d.id}">Borcu Sil</button>`;$('#debtDetailDialog').showModal()}
async function initSupabase(){if(!cloud.url||!cloud.key||!window.supabase)return;try{sb=window.supabase.createClient(cloud.url,cloud.key,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});const {data}=await sb.auth.getSession();session=data.session;sb.auth.onAuthStateChange((_event,s)=>{session=s;renderCloud()});if(session)await pullCloud()}catch(e){console.error(e);toast('Bulut bağlantısı başlatılamadı.') }renderCloud()}
async function login(){if(!sb)return toast('Önce bağlantı bilgilerini kaydedin.');const email=$('#authEmail').value.trim(),password=$('#authPassword').value;if(!email||!password)return toast('E-posta ve şifre gerekli.');const hasLocal=state.debts.length||state.expenses.length||state.payments.length;const {data,error}=await sb.auth.signInWithPassword({email,password});if(error)return alert(error.message);session=data.session;if(hasLocal&&confirm('Bu telefonda yerel kayıtlar var. Önce bunlar ortak buluta birleştirilsin mi?'))await pushLocalToCloud();else await pullCloud();renderAll();toast('Kurum hesabına giriş yapıldı.')}
async function register(){if(!sb)return;const email=$('#authEmail').value.trim(),password=$('#authPassword').value;if(!email||password.length<6)return toast('Geçerli e-posta ve en az 6 karakter şifre girin.');const {data,error}=await sb.auth.signUp({email,password});if(error)return alert(error.message);session=data.session;if(!session){alert('Hesap oluşturuldu. Supabase e-posta doğrulaması açıksa gelen kutusundaki bağlantıyı onaylayın, sonra giriş yapın.');return}await pushLocalToCloud();toast('Kurum hesabı oluşturuldu.')}
async function logout(){if(sb)await sb.auth.signOut();session=null;renderCloud();toast('Bulut hesabından çıkıldı.')}
async function cloudUpsertDebt(d){if(!session)return;const row={id:d.id,user_id:session.user.id,ad:d.name,tur:d.type,ilk_tutar:d.original,kalan_tutar:d.balance,faiz_orani:d.rate,aylik_odeme:d.minimum,vade_tarihi:d.dueDate||null,tekrar:d.frequency,notlar:d.notes,durum:d.status,ekleyen:d.addedBy||deviceName()};const {error}=await sb.from('borclar').upsert(row);if(error)throw error}
async function cloudUpsertExpense(x){if(!session)return;const row={id:x.id,user_id:session.user.id,tarih:x.date,kategori:x.category,aciklama:x.description,tutar:x.amount,odeme_yontemi:x.method,notlar:x.notes,ekleyen:x.addedBy||deviceName()};const {error}=await sb.from('harcamalar').upsert(row);if(error)throw error}
async function cloudUpsertPayment(p){if(!session)return;const row={id:p.id,user_id:session.user.id,borc_id:p.debtId,tarih:p.date,tutar:p.amount,notlar:p.notes||'',ekleyen:p.addedBy||deviceName()};const {error}=await sb.from('odemeler').upsert(row);if(error)throw error}
async function cloudUpsertSettings(){if(!session)return;const row={user_id:session.user.id,kurum_adi:state.budget.orgName||'',aylik_gelir:+state.budget.income||0,sabit_gider:+state.budget.fixedExpenses||0,rezerv:+state.budget.reserve||0};const {error}=await sb.from('ayarlar').upsert(row);if(error)throw error}
async function deleteCloud(table,id){if(!session)return;const {error}=await sb.from(table).delete().eq('id',id);if(error)throw error}
async function pullCloud(){if(!session||syncing)return;syncing=true;$('#syncBadge').textContent='Eşitleniyor';$('#syncBadge').className='status-badge syncing';try{const [bd,ex,pa,se]=await Promise.all([sb.from('borclar').select('*'),sb.from('harcamalar').select('*'),sb.from('odemeler').select('*'),sb.from('ayarlar').select('*').maybeSingle()]);for(const r of [bd,ex,pa,se])if(r.error)throw r.error;state.debts=(bd.data||[]).map(normalizeDebt);state.expenses=(ex.data||[]).map(normalizeExpense);state.payments=(pa.data||[]).map(normalizePayment);if(se.data)state.budget={orgName:se.data.kurum_adi||'',income:+se.data.aylik_gelir||0,fixedExpenses:+se.data.sabit_gider||0,reserve:+se.data.rezerv||0};saveState(false);renderAll();}catch(e){console.error(e);alert(`Bulut senkronizasyon hatası: ${e.message}\n\nSupabase'de kurulum.sql dosyasının çalıştırıldığını kontrol edin.`)}finally{syncing=false;renderCloud()}}
async function pushLocalToCloud(){if(!session||syncing)return;syncing=true;try{for(const d0 of state.debts){const d=normalizeDebt(d0);await cloudUpsertDebt(d)}for(const x0 of state.expenses){const x=normalizeExpense(x0);await cloudUpsertExpense(x)}for(const p0 of state.payments){const p=normalizePayment(p0);await cloudUpsertPayment(p)}await cloudUpsertSettings();syncing=false;await pullCloud();toast('Yerel veri bulutla birleştirildi.');if($('#cloudDialog')?.open)$('#cloudDialog').close()}catch(e){console.error(e);alert(`Buluta gönderilemedi: ${e.message}`)}finally{syncing=false;renderCloud()}}
async function saveDebtCloud(d){if(session){try{await cloudUpsertDebt(d);await pullCloud()}catch(e){alert(`Bulut kayıt hatası: ${e.message}`)}}}
async function saveExpenseCloud(x){if(session){try{await cloudUpsertExpense(x);await pullCloud()}catch(e){alert(`Bulut kayıt hatası: ${e.message}`)}}}
async function saveBudgetCloud(){if(session){try{await cloudUpsertSettings();await pullCloud()}catch(e){alert(`Bulut kayıt hatası: ${e.message}`)}}}
async function payCloud(debtId,amount,date,notes){if(!session)return false;const {error}=await sb.rpc('borc_odeme_kaydet',{p_borc_id:debtId,p_tutar:amount,p_tarih:date,p_notlar:notes||'',p_ekleyen:deviceName()});if(error){alert(`Ödeme kaydedilemedi: ${error.message}`);return true}await pullCloud();return true}

$$('.nav-btn').forEach(b=>b.addEventListener('click',()=>openView(b.dataset.view)));$$('[data-open]').forEach(b=>b.addEventListener('click',()=>openView(b.dataset.open)));
$('#addDebtBtn').onclick=()=>openDebtDialog();$('#addExpenseBtn').onclick=()=>openExpenseDialog();$('#fab').onclick=()=>openExpenseDialog();$('#addPaymentBtn').onclick=()=>openPaymentDialog();
$$('.close-dialog').forEach(b=>b.onclick=()=>b.closest('dialog').close());
$('#debtSearch').oninput=renderDebts;$('#debtFilter').onchange=renderDebts;$('#expenseSearch').oninput=renderExpenses;$('#expenseMonth').onchange=renderExpenses;
$('#debtForm').addEventListener('submit',async e=>{e.preventDefault();const fd=Object.fromEntries(new FormData(e.target));const old=state.debts.map(normalizeDebt).find(x=>x.id===fd.id);const d=normalizeDebt({...old,...fd,id:fd.id||uid(),original:+fd.original,balance:+fd.balance,rate:+fd.rate||0,minimum:+fd.minimum||0,status:+fd.balance<=0?'closed':'active',addedBy:old?.addedBy||deviceName(),createdAt:old?.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString()});const i=state.debts.findIndex(x=>x.id===d.id);if(i>=0)state.debts[i]=d;else state.debts.push(d);saveState();$('#debtDialog').close();toast(i>=0?'Borç güncellendi.':'Borç eklendi.');await saveDebtCloud(d)});
$('#expenseForm').addEventListener('submit',async e=>{e.preventDefault();const fd=Object.fromEntries(new FormData(e.target));const old=state.expenses.map(normalizeExpense).find(x=>x.id===fd.id);const x=normalizeExpense({...old,...fd,id:fd.id||uid(),amount:+fd.amount,addedBy:old?.addedBy||deviceName(),createdAt:old?.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString()});const i=state.expenses.findIndex(v=>v.id===x.id);if(i>=0)state.expenses[i]=x;else state.expenses.push(x);saveState();$('#expenseDialog').close();toast(i>=0?'Harcama güncellendi.':'Harcama eklendi.');await saveExpenseCloud(x)});
$('#paymentForm').addEventListener('submit',async e=>{e.preventDefault();const fd=Object.fromEntries(new FormData(e.target)),amount=+fd.amount;if(amount<=0)return;const d=state.debts.map(normalizeDebt).find(x=>x.id===fd.debtId);if(!d)return;if(amount>d.balance&&!confirm(`Ödeme kalan borçtan ${money(amount-d.balance)} fazla. Yine de kaydedilsin mi?`))return;if(await payCloud(d.id,amount,fd.date,fd.notes)){e.target.closest('dialog').close();toast('Ödeme buluta kaydedildi.');return}state.payments.push(normalizePayment({id:uid(),debtId:d.id,amount,date:fd.date,notes:fd.notes||'',addedBy:deviceName()}));const raw=state.debts.find(x=>x.id===d.id);raw.balance=Math.max(0,d.balance-amount);raw.status=raw.balance<=0?'closed':'active';if(d.frequency==='monthly'&&d.dueDate&&parseDate(fd.date)>=new Date(parseDate(d.dueDate).getTime()-7*86400000))raw.dueDate=addMonths(parseDate(d.dueDate),1).toISOString().slice(0,10);saveState();$('#paymentDialog').close();toast(raw.balance<=0?'Borç kapandı.':'Ödeme kaydedildi.')});
$('#budgetForm').addEventListener('submit',async e=>{e.preventDefault();const fd=Object.fromEntries(new FormData(e.target));state.budget={orgName:fd.orgName||'',income:+fd.income||0,fixedExpenses:+fd.fixedExpenses||0,reserve:+fd.reserve||0};saveState();toast('Bütçe kaydedildi.');await saveBudgetCloud()});
$('#saveDeviceName').onclick=()=>{const name=$('#deviceName').value.trim();localStorage.setItem(DEVICE_KEY,name||'Bu telefon');toast('Telefon adı kaydedildi.')};
document.addEventListener('click',async e=>{const card=e.target.closest('[data-debt]');if(card)showDebtDetail(card.dataset.debt);const exp=e.target.closest('[data-expense]');if(exp){const x=state.expenses.map(normalizeExpense).find(v=>v.id===exp.dataset.expense);if(x&&confirm(`${x.description}\n${money(x.amount)}\n\nDüzenlemek ister misiniz?`))openExpenseDialog(x)}const pay=e.target.closest('[data-pay]');if(pay){$('#debtDetailDialog').close();openPaymentDialog(pay.dataset.pay)}const edit=e.target.closest('[data-edit-debt]');if(edit){$('#debtDetailDialog').close();openDebtDialog(state.debts.map(normalizeDebt).find(x=>x.id===edit.dataset.editDebt))}const del=e.target.closest('[data-delete-debt]');if(del&&confirm('Bu borç ve ödeme geçmişi silinsin mi?')){const id=del.dataset.deleteDebt;if(session){try{await deleteCloud('borclar',id);await pullCloud()}catch(er){return alert(er.message)}}else{state.debts=state.debts.filter(x=>x.id!==id);state.payments=state.payments.filter(x=>normalizePayment(x).debtId!==id);saveState()}$('#debtDetailDialog').close();toast('Borç silindi.')}});
$('#exportBtn').onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`kurum-finans-yedek-${todayISO()}.json`;a.click();URL.revokeObjectURL(a.href)};
$('#importInput').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const data=JSON.parse(await f.text());state={...clone(defaultState),...data};saveState();toast('Yedek yüklendi.');if(session&&confirm('Yedek buluta da gönderilsin mi?'))await pushLocalToCloud()}catch{alert('Geçersiz yedek dosyası.')}e.target.value=''};
$('#resetBtn').onclick=()=>{if(confirm('Yalnız bu telefondaki yerel önbellek temizlenecek. Buluttaki veriler silinmez. Devam?')){state=clone(defaultState);saveState();toast('Yerel veri temizlendi.')}};
$('#demoBtn').onclick=()=>{if((state.debts.length||state.expenses.length)&&!confirm('Demo verileri mevcut kayıtlara eklenecek. Devam?'))return;const t=new Date(),d1=new Date(t),d2=new Date(t);d1.setDate(t.getDate()+3);d2.setDate(t.getDate()+11);state.debts.push(normalizeDebt({id:uid(),name:'İşletme Kredi Kartı',type:'Kredi Kartı',original:90000,balance:48200,rate:49,minimum:6500,dueDate:d1.toISOString().slice(0,10),frequency:'monthly',addedBy:deviceName()}),normalizeDebt({id:uid(),name:'İşletme Kredisi',type:'İşletme Kredisi',original:180000,balance:122000,rate:34,minimum:12500,dueDate:d2.toISOString().slice(0,10),frequency:'monthly',addedBy:deviceName()}));state.expenses.push(normalizeExpense({id:uid(),date:todayISO(),category:'Telefon / İnternet',description:'İnternet faturası',amount:1250,method:'Banka',addedBy:deviceName()}),normalizeExpense({id:uid(),date:todayISO(),category:'Malzeme',description:'Ofis sarf malzemesi',amount:860,method:'Kredi Kartı',addedBy:deviceName()}));state.budget={orgName:'Demo Kurum',income:120000,fixedExpenses:65000,reserve:15000};saveState();toast('Demo verisi yüklendi.')};
function openCloudDialog(){if(cloud.url)$('#supabaseUrl').value=cloud.url;if(cloud.key)$('#supabaseKey').value=cloud.key;renderCloud();$('#cloudDialog').showModal()}
$('#openCloudSetup').onclick=openCloudDialog;$('#cloudSetupBtn').onclick=openCloudDialog;
$('#saveCloudConfig').onclick=async()=>{const url=$('#supabaseUrl').value.trim().replace(/\/$/,''),key=$('#supabaseKey').value.trim();if(!/^https:\/\/.+\.supabase\.co$/.test(url)||key.length<20)return toast('Geçerli Supabase URL ve key girin.');cloud={url,key};localStorage.setItem(CONFIG_KEY,JSON.stringify(cloud));sb=null;session=null;await initSupabase();renderCloud();toast('Bulut bağlantısı kaydedildi.')};
$('#loginBtn').onclick=login;$('#registerBtn').onclick=register;$('#logoutBtn').onclick=logout;$('#cloudLogoutButton').onclick=logout;$('#syncNowBtn').onclick=()=>session?pullCloud():toast('Önce kurum hesabına giriş yapın.');$('#cloudSyncButton').onclick=pushLocalToCloud;
window.addEventListener('focus',()=>{if(session)pullCloud()});document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&session)pullCloud()});setInterval(()=>{if(session&&document.visibilityState==='visible')pullCloud()},20000);
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('#installBtn').classList.remove('hidden')});$('#installBtn').onclick=async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$('#installBtn').classList.add('hidden')};
if(location.search.includes('error_code=')||location.hash.includes('error_code=')){history.replaceState({},document.title,location.pathname)}
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(console.error);
renderAll();initSupabase();
